volumes:
  yagpdb_docker_redis:
    external: true
  yagpdb_docker_cert_cache:
    external: true
  yagpdb_docker_soundboard:
    external: true
  # yagpdb:
  #   external: true

networks:
  web:
    external: true
  net_redis:
    external: true

services:
  app:
    #image: PUT_YOUR_OWN_IMAGE_HERE
    container_name: yagpdb
    build:
      context: ../
      dockerfile: yagpdb_docker/Dockerfile
    restart: unless-stopped
    command:
      # - "/app/yagpdb"
      - "-all"
      - "-pa"
      - "-exthttps=false"
      - "-https=true"
    depends_on:
      - redis
    networks:
      - web
      - net_redis
    volumes:
      - yagpdb_docker_cert_cache:/app/cert
      - yagpdb_docker_soundboard:/app/soundboard
    # ports:
    #   - '80:80'
    #   - '443:443'
    env_file:
      - app.env

  redis:
    image: docker.io/redis
    container_name: redis
    restart: unless-stopped
    networks:
      - net_redis
    volumes:
      - yagpdb_docker_redis:/data